name: Renovate
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'patch-renovate-*'
env:
  LOG_LEVEL: debug
  RENOVATE_CONFIG_FILE: renovate.json5
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate@whitesourcesoftware.com>"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.106.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}

